### PR TITLE
Is that space even needed?

### PR DESCRIPTION
**Pull request by iksaku**

### CODE REVIEW

**Comment by jasonlong** [comment]
:thumbsup:

**Comment by iksaku** [comment]
I really love this theme :'D

**Comment by jasonlong** [comment]
Thanks! :sparkles:

**Comment by iksaku** [comment]
I'm currently trying to make the theme compatible with Jekyll... It would be cool if you make some kind of "wrapper" to adapt the style to Jekyll's behaviour

**Comment by jasonlong** [comment]
Another user maintains a Jekyll port of one of my other themes, so you might find that helpful.

https://github.com/pietromenna/jekyll-architect-theme

If you get it working, let me know and I'll add a link to the README here.

**Comment by iksaku** [comment]
Wow! Thanks! I will work on it ;) if I'm able to get something I will let you know ;)

**Pull request merged**
